-- Insert all 11 products (adjust prices as needed)
INSERT INTO products (slug, title, description, price, currency, file_key, file_name, download_limit, category, tags, is_bundle, image_url) VALUES
('gina-ballerina-eats-a-rainbow-bundle', 'Gina Ballerina Eats A Rainbow Bundle', 'A colourful bundle of dance activities for kids. Includes printable games, colouring sheets, and a story.', 149.00, 'NAD', 'bundles/rainbow-bundle.zip', 'rainbow-bundle.zip', 5, 'kids', ARRAY['pink','purple','rainbow'], true, '/images/rainbow.jpg'),
('gina-ballerina-easter-bundle', 'Gina Ballerina Easter Bundle', 'Easter themed dance fun: colouring, puzzles, and an Easter bunny dance routine.', 149.00, 'NAD', 'bundles/easter-bundle.zip', 'easter-bundle.zip', 5, 'kids', ARRAY['pink','purple','easter'], true, '/images/easter.jpg'),
('gina-ballerina-and-the-easter-bunny-story', 'Gina Ballerina and the Easter Bunny Story', 'A charming PDF storybook about Gina and the Easter Bunny.', 49.00, 'NAD', 'stories/easter-story.pdf', 'easter-story.pdf', 3, 'kids', ARRAY['pink','easter'], false, '/images/story.jpg'),
('gina-ballerina-and-the-easter-bunny-coloring-book', 'Gina Ballerina Easter Bunny Coloring Book', 'Printable coloring pages with Gina and the Easter Bunny.', 39.00, 'NAD', 'coloring/easter-coloring.pdf', 'easter-coloring.pdf', 3, 'kids', ARRAY['purple','easter'], false, '/images/coloring.jpg'),
('gina-ballerina-goes-to-the-beach-dance-bundle', 'Gina Ballerina Beach Dance Bundle', 'Summer beach dance pack: activities, coloring, and a dance tutorial.', 149.00, 'NAD', 'bundles/beach-bundle.zip', 'beach-bundle.zip', 5, 'kids', ARRAY['pink','blue','beach'], true, '/images/beach.jpg'),
('gina-ballerina-and-mom-bundle', 'Gina Ballerina and Mom Bundle', 'Mother-child dance and craft activities to do together.', 129.00, 'NAD', 'bundles/mom-bundle.zip', 'mom-bundle.zip', 5, 'kids', ARRAY['pink','purple','mom'], true, '/images/mom.jpg'),
('adult-relaxing-dance-themed-mandala-coloring-book', 'Adult Relaxing Dance Themed Mandala Coloring Book', 'Intricate mandala designs inspired by dance – relax and colour.', 79.00, 'NAD', 'adult/mandala-coloring.pdf', 'mandala-coloring.pdf', 3, 'adult', ARRAY['purple','grey','mandala'], false, '/images/mandala.jpg'),
('dance-themed-birthday-calendar', 'Dance Themed Birthday Calendar', 'Printable monthly calendar with dance illustrations.', 29.00, 'NAD', 'printables/birthday-calendar.pdf', 'birthday-calendar.pdf', 3, 'printable', ARRAY['pink','purple','calendar'], false, '/images/calendar.jpg'),
('elegant-dance-themed-planner-page', 'Elegant Dance Themed Planner Page', 'A single-page weekly planner insert with dance theme.', 19.00, 'NAD', 'printables/planner-page.pdf', 'planner-page.pdf', 3, 'printable', ARRAY['purple','grey','planner'], false, '/images/planner.jpg'),
('dance-wall-poster-calendar', 'Dance Wall Poster Calendar', 'Large wall calendar (A3) with dance photography.', 49.00, 'NAD', 'printables/wall-calendar.pdf', 'wall-calendar.pdf', 3, 'printable', ARRAY['pink','calendar'], false, '/images/wall-calendar.jpg'),
('mothersday-bundle', 'Mothersday Bundle', 'Special bundle for Mother''s Day: cards, activities, and a dance routine.', 149.00, 'NAD', 'bundles/mothersday.zip', 'mothersday.zip', 5, 'kids', ARRAY['pink','purple','mothersday'], true, '/images/mothersday.jpg');